package hub.nishat.net.model.AM;

import hub.nishat.net.model.VO.General.VO_EmpHierarchySummaryImpl;
import hub.nishat.net.model.VO.HR.VO_AttendanceHRImpl;
import hub.nishat.net.model.VO.Supervisor.VO_LeaveRequestsImpl;
import hub.nishat.net.model.VO.Supervisor.VO_SupervisorOrgChartImpl;
import hub.nishat.net.model.VO.VO_AtdPostingImpl;
import hub.nishat.net.model.VO.VO_AttendanceImpl;


import hub.nishat.net.model.VO.VO_ExceptionReqImpl;


import hub.nishat.net.model.VO.VO_MISSING_MINUTESImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 11 15:39:18 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HubModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HubModuleImpl() {
    }

    /**
     * Container's getter for VO_Attendance1.
     * @return VO_Attendance1
     */
    public VO_AttendanceImpl getVO_Attendance1() {
        return (VO_AttendanceImpl)findViewObject("VO_Attendance1");
    }

    /**
     * Container's getter for VO_Months1.
     * @return VO_Months1
     */
    public ViewObjectImpl getVO_Months1() {
        return (ViewObjectImpl)findViewObject("VO_Months1");
    }

    /**
     * Container's getter for VO_Years1.
     * @return VO_Years1
     */
    public ViewObjectImpl getVO_Years1() {
        return (ViewObjectImpl)findViewObject("VO_Years1");
    }

    /**
     * Container's getter for VO_LeaveTypes1.
     * @return VO_LeaveTypes1
     */
    public ViewObjectImpl getVO_LeaveTypes1() {
        return (ViewObjectImpl)findViewObject("VO_LeaveTypes1");
    }

    /**
     * Container's getter for VO_Leaves1.
     * @return VO_Leaves1
     */
    public ViewObjectImpl getVO_Leaves1() {
        return (ViewObjectImpl)findViewObject("VO_Leaves1");
    }
    public Number getLeaveSequence(){
        SequenceImpl leaveSeq = new SequenceImpl("xx_E_portal_leave_seq",getDBTransaction());
        return leaveSeq.getSequenceNumber();
    }
    public Number getApprovalSequence(){
        SequenceImpl approvalSeq = new SequenceImpl("xx_E_portal_approval_seq",getDBTransaction());
        return approvalSeq.getSequenceNumber();
    }
    public Number getAttendanceSequence(){
        SequenceImpl attendanceSeq = new SequenceImpl("xx_e_portal_sequence",getDBTransaction());
        return attendanceSeq.getSequenceNumber();
    }
    public Number getPostingSequence(){
        SequenceImpl attendanceSeq = new SequenceImpl("xx_e_portal_atd_posting_seq",getDBTransaction());
        return attendanceSeq.getSequenceNumber();
    }
    
    public Number getLfaSequence(){
        SequenceImpl lfaSeq = new SequenceImpl("xx_e_portal_emp_lfa_Seq",getDBTransaction());
        return lfaSeq.getSequenceNumber();
    }
    public Number getConsumedLeaveSequence(){
        SequenceImpl lfaSeq = new SequenceImpl("Xx_e_portal_consumed_leave_seq",getDBTransaction());
        return lfaSeq.getSequenceNumber();
    }
    public Number getExceptionReqSequence(){
        SequenceImpl lfaSeq = new SequenceImpl("xx_e_portal_exception_Seq",getDBTransaction());
        return lfaSeq.getSequenceNumber();
    }
    
    

    /**
     * Container's getter for VO_LeaveCriteria1.
     * @return VO_LeaveCriteria1
     */
    public ViewObjectImpl getVO_LeaveCriteria1() {
        return (ViewObjectImpl)findViewObject("VO_LeaveCriteria1");
    }

    /**
     * Container's getter for VO_LateSitting1.
     * @return VO_LateSitting1
     */
    public ViewObjectImpl getVO_LateSitting1() {
        return (ViewObjectImpl)findViewObject("VO_LateSitting1");
    }

    /**
     * Container's getter for VO_LeaveApproval1.
     * @return VO_LeaveApproval1
     */
    public ViewObjectImpl getVO_LeaveApproval1() {
        return (ViewObjectImpl)findViewObject("VO_LeaveApproval1");
    }

    

    

    /**
     * Container's getter for YearLov1.
     * @return YearLov1
     */
    public ViewObjectImpl getYearLov1() {
        return (ViewObjectImpl)findViewObject("YearLov1");
    }

    /**
     * Container's getter for VO_EmpAttendance1.
     * @return VO_EmpAttendance1
     */
    public ViewObjectImpl getVO_EmpAttendance1() {
        return (ViewObjectImpl)findViewObject("VO_EmpAttendance1");
    }

    /**
     * Container's getter for VO_EmpHierarchySummary1.
     * @return VO_EmpHierarchySummary1
     */
    public ViewObjectImpl getVO_EmpHierarchySummary1() {
        return (ViewObjectImpl)findViewObject("VO_EmpHierarchySummary1");
    }

  

    /**
     * Container's getter for VO_LeavesAndPolicyExceptions1.
     * @return VO_LeavesAndPolicyExceptions1
     */
    public ViewObjectImpl getVO_LeavesAndPolicyExceptions1() {
        return (ViewObjectImpl)findViewObject("VO_LeavesAndPolicyExceptions1");
    }


    /**
     * Container's getter for VO_LeaveBalanceReport1.
     * @return VO_LeaveBalanceReport1
     */
    public ViewObjectImpl getVO_LeaveBalanceReport1() {
        return (ViewObjectImpl)findViewObject("VO_LeaveBalanceReport1");
    }

   

    /**
     * Container's getter for VO_EmployeeLeaveBalance1.
     * @return VO_EmployeeLeaveBalance1
     */
    public ViewObjectImpl getVO_EmployeeLeaveBalance1() {
        return (ViewObjectImpl)findViewObject("VO_EmployeeLeaveBalance1");
    }

    /**
     * Container's getter for VO_EmptyAttendance1.
     * @return VO_EmptyAttendance1
     */
    public ViewObjectImpl getVO_EmptyAttendance1() {
        return (ViewObjectImpl)findViewObject("VO_EmptyAttendance1");
    }

    /**
     * Container's getter for VO_AtdPosting1.
     * @return VO_AtdPosting1
     */
    public ViewObjectImpl getVO_AtdPosting1() {
        return (ViewObjectImpl)findViewObject("VO_AtdPosting1");
    }

    /**
     * Container's getter for VO_AttendanceHR1.
     * @return VO_AttendanceHR1
     */
    public ViewObjectImpl getVO_AttendanceHR1() {
        return (ViewObjectImpl)findViewObject("VO_AttendanceHR1");
    }

    /**
     * Container's getter for VO_ActiveEmployees1.
     * @return VO_ActiveEmployees1
     */
    public ViewObjectImpl getVO_ActiveEmployees1() {
        return (ViewObjectImpl)findViewObject("VO_ActiveEmployees1");
    }

    /**
     * Container's getter for VO_ActiveEmployees2.
     * @return VO_ActiveEmployees2
     */
    public ViewObjectImpl getVO_ActiveEmployees2() {
        return (ViewObjectImpl)findViewObject("VO_ActiveEmployees2");
    }

    /**
     * Container's getter for VO_AttendanceHR2.
     * @return VO_AttendanceHR2
     */
    public ViewObjectImpl getVO_AttendanceHR2() {
        return (ViewObjectImpl)findViewObject("VO_AttendanceHR2");
    }

    /**
     * Container's getter for VL_Emp2Att.
     * @return VL_Emp2Att
     */
    public ViewLinkImpl getVL_Emp2Att() {
        return (ViewLinkImpl)findViewLink("VL_Emp2Att");
    }

    /**
     * Container's getter for DepartmentLov1.
     * @return DepartmentLov1
     */
    public ViewObjectImpl getDepartmentLov1() {
        return (ViewObjectImpl)findViewObject("DepartmentLov1");
    }


    /**
     * Container's getter for VO_ActiveEmployees3.
     * @return VO_ActiveEmployees3
     */
    public ViewObjectImpl getVO_ActiveEmployees3() {
        return (ViewObjectImpl)findViewObject("VO_ActiveEmployees3");
    }

    /**
     * Container's getter for VL_Emp2Depart.
     * @return VL_Emp2Depart
     */
    public ViewLinkImpl getVL_Emp2Depart() {
        return (ViewLinkImpl)findViewLink("VL_Emp2Depart");
    }

    /**
     * Container's getter for DepartmentLov3.
     * @return DepartmentLov3
     */
    public ViewObjectImpl getDepartmentLov3() {
        return (ViewObjectImpl)findViewObject("DepartmentLov3");
    }

    /**
     * Container's getter for VO_ActiveEmployees4.
     * @return VO_ActiveEmployees4
     */
    public ViewObjectImpl getVO_ActiveEmployees4() {
        return (ViewObjectImpl)findViewObject("VO_ActiveEmployees4");
    }

    /**
     * Container's getter for VL_Department2Emp.
     * @return VL_Department2Emp
     */
    public ViewLinkImpl getVL_Department2Emp() {
        return (ViewLinkImpl)findViewLink("VL_Department2Emp");
    }

    /**
     * Container's getter for VO_AttendanceHR3.
     * @return VO_AttendanceHR3
     */
    public ViewObjectImpl getVO_AttendanceHR3() {
        return (ViewObjectImpl)findViewObject("VO_AttendanceHR3");
    }

    /**
     * Container's getter for VL_Emp2Att1.
     * @return VL_Emp2Att1
     */
    public ViewLinkImpl getVL_Emp2Att1() {
        return (ViewLinkImpl)findViewLink("VL_Emp2Att1");
    }

    /**
     * Container's getter for MonthLov1.
     * @return MonthLov1
     */
    public ViewObjectImpl getMonthLov1() {
        return (ViewObjectImpl)findViewObject("MonthLov1");
    }

    /**
     * Container's getter for VO_HRPosting1.
     * @return VO_HRPosting1
     */
    public ViewObjectImpl getVO_HRPosting1() {
        return (ViewObjectImpl)findViewObject("VO_HRPosting1");
    }

    /**
     * Container's getter for VO_AttendanceHR4.
     * @return VO_AttendanceHR4
     */
    public VO_AttendanceHRImpl getVO_AttendanceHR4() {
        return (VO_AttendanceHRImpl)findViewObject("VO_AttendanceHR4");
    }




    /**
     * Container's getter for VL_Atd2Posting.
     * @return VL_Atd2Posting
     */
    public ViewLinkImpl getVL_Atd2Posting() {
        return (ViewLinkImpl)findViewLink("VL_Atd2Posting");
    }

    /**
     * Container's getter for EmployeeLov1.
     * @return EmployeeLov1
     */
    public ViewObjectImpl getEmployeeLov1() {
        return (ViewObjectImpl)findViewObject("EmployeeLov1");
    }

    /**
     * Container's getter for VO_EmpDepartmentCombination1.
     * @return VO_EmpDepartmentCombination1
     */
    public ViewObjectImpl getVO_EmpDepartmentCombination1() {
        return (ViewObjectImpl)findViewObject("VO_EmpDepartmentCombination1");
    }

    /**
     * Container's getter for DepartmentLov2.
     * @return DepartmentLov2
     */
    public ViewObjectImpl getDepartmentLov2() {
        return (ViewObjectImpl)findViewObject("DepartmentLov2");
    }

    /**
     * Container's getter for EmployeeLov2.
     * @return EmployeeLov2
     */
    public ViewObjectImpl getEmployeeLov2() {
        return (ViewObjectImpl)findViewObject("EmployeeLov2");
    }

    /**
     * Container's getter for VL_DptEmp.
     * @return VL_DptEmp
     */
    public ViewLinkImpl getVL_DptEmp() {
        return (ViewLinkImpl)findViewLink("VL_DptEmp");
    }

    /**
     * Container's getter for VO_EmpFlexi1.
     * @return VO_EmpFlexi1
     */
    public ViewObjectImpl getVO_EmpFlexi1() {
        return (ViewObjectImpl)findViewObject("VO_EmpFlexi1");
    }

    /**
     * Container's getter for EmployeeLov3.
     * @return EmployeeLov3
     */
    public ViewObjectImpl getEmployeeLov3() {
        return (ViewObjectImpl)findViewObject("EmployeeLov3");
    }


    /**
     * Container's getter for VL_EmpFlexi.
     * @return VL_EmpFlexi
     */
    public ViewLinkImpl getVL_EmpFlexi() {
        return (ViewLinkImpl)findViewLink("VL_EmpFlexi");
    }

    /**
     * Container's getter for VO_Employees1.
     * @return VO_Employees1
     */
    public ViewObjectImpl getVO_Employees1() {
        return (ViewObjectImpl)findViewObject("VO_Employees1");
    }

    /**
     * Container's getter for FlexiHoursLov1.
     * @return FlexiHoursLov1
     */
    public ViewObjectImpl getFlexiHoursLov1() {
        return (ViewObjectImpl)findViewObject("FlexiHoursLov1");
    }

    /**
     * Container's getter for EmpTypeLov1.
     * @return EmpTypeLov1
     */
    public ViewObjectImpl getEmpTypeLov1() {
        return (ViewObjectImpl)findViewObject("EmpTypeLov1");
    }

    /**
     * Container's getter for VO_EmpLFARequests1.
     * @return VO_EmpLFARequests1
     */
    public ViewObjectImpl getVO_EmpLFARequests1() {
        return (ViewObjectImpl)findViewObject("VO_EmpLFARequests1");
    }

    /**
     * Container's getter for VO_EmpLeaves1.
     * @return VO_EmpLeaves1
     */
    public ViewObjectImpl getVO_EmpLeaves1() {
        return (ViewObjectImpl)findViewObject("VO_EmpLeaves1");
    }

    /**
     * Container's getter for VO_ProbLeaves1.
     * @return VO_ProbLeaves1
     */
    public ViewObjectImpl getVO_ProbLeaves1() {
        return (ViewObjectImpl)findViewObject("VO_ProbLeaves1");
    }

    /**
     * Container's getter for VO_ConsumedLeaves1.
     * @return VO_ConsumedLeaves1
     */
    public ViewObjectImpl getVO_ConsumedLeaves1() {
        return (ViewObjectImpl)findViewObject("VO_ConsumedLeaves1");
    }

    /**
     * Container's getter for VO_LeaveRequests1.
     * @return VO_LeaveRequests1
     */
    public ViewObjectImpl getVO_LeaveRequests1() {
        return (ViewObjectImpl)findViewObject("VO_LeaveRequests1");
    }

    /**
     * Container's getter for VO_AttendanceEvents1.
     * @return VO_AttendanceEvents1
     */
    public ViewObjectImpl getVO_AttendanceEvents1() {
        return (ViewObjectImpl)findViewObject("VO_AttendanceEvents1");
    }

    /**
     * Container's getter for VO_Attendance2.
     * @return VO_Attendance2
     */
    public VO_AttendanceImpl getVO_Attendance2() {
        return (VO_AttendanceImpl)findViewObject("VO_Attendance2");
    }

    /**
     * Container's getter for VO_AttendanceEvents2.
     * @return VO_AttendanceEvents2
     */
    public ViewObjectImpl getVO_AttendanceEvents2() {
        return (ViewObjectImpl)findViewObject("VO_AttendanceEvents2");
    }

    /**
     * Container's getter for VL_Attendance_Events.
     * @return VL_Attendance_Events
     */
    public ViewLinkImpl getVL_Attendance_Events() {
        return (ViewLinkImpl)findViewLink("VL_Attendance_Events");
    }

    /**
     * Container's getter for VO_ExceptionReq1.
     * @return VO_ExceptionReq1
     */
    public ViewObjectImpl getVO_ExceptionReq1() {
        return (ViewObjectImpl)findViewObject("VO_ExceptionReq1");
    }

    /**
     * Container's getter for VO_AttendanceIrregularityV1.
     * @return VO_AttendanceIrregularityV1
     */
    public ViewObjectImpl getVO_AttendanceIrregularityV1() {
        return (ViewObjectImpl)findViewObject("VO_AttendanceIrregularityV1");
    }

    /**
     * Container's getter for VO_LeaveBalance1.
     * @return VO_LeaveBalance1
     */
    public ViewObjectImpl getVO_LeaveBalance1() {
        return (ViewObjectImpl)findViewObject("VO_LeaveBalance1");
    }

    /**
     * Container's getter for VO_ActiveEmployees5.
     * @return VO_ActiveEmployees5
     */
    public ViewObjectImpl getVO_ActiveEmployees5() {
        return (ViewObjectImpl)findViewObject("VO_ActiveEmployees5");
    }

    /**
     * Container's getter for VO_ConsumedLeaves2.
     * @return VO_ConsumedLeaves2
     */
    public ViewObjectImpl getVO_ConsumedLeaves2() {
        return (ViewObjectImpl)findViewObject("VO_ConsumedLeaves2");
    }

    /**
     * Container's getter for VL_Emp2Leaves.
     * @return VL_Emp2Leaves
     */
    public ViewLinkImpl getVL_Emp2Leaves() {
        return (ViewLinkImpl)findViewLink("VL_Emp2Leaves");
    }

    /**
     * Container's getter for VO_Departments1.
     * @return VO_Departments1
     */
    public ViewObjectImpl getVO_Departments1() {
        return (ViewObjectImpl)findViewObject("VO_Departments1");
    }

    /**
     * Container's getter for VO_Departments2.
     * @return VO_Departments2
     */
    public ViewObjectImpl getVO_Departments2() {
        return (ViewObjectImpl)findViewObject("VO_Departments2");
    }

    /**
     * Container's getter for VO_Employees2.
     * @return VO_Employees2
     */
    public ViewObjectImpl getVO_Employees2() {
        return (ViewObjectImpl)findViewObject("VO_Employees2");
    }

    /**
     * Container's getter for VL_Dpt2Emp.
     * @return VL_Dpt2Emp
     */
    public ViewLinkImpl getVL_Dpt2Emp() {
        return (ViewLinkImpl)findViewLink("VL_Dpt2Emp");
    }

    /**
     * Container's getter for VO_XxEPortalUsers1.
     * @return VO_XxEPortalUsers1
     */
    public ViewObjectImpl getVO_XxEPortalUsers1() {
        return (ViewObjectImpl)findViewObject("VO_XxEPortalUsers1");
    }

    /**
     * Container's getter for VO_HolidayCalendar1.
     * @return VO_HolidayCalendar1
     */
    public ViewObjectImpl getVO_HolidayCalendar1() {
        return (ViewObjectImpl)findViewObject("VO_HolidayCalendar1");
    }

    /**
     * Container's getter for VO_XXEPortalAttendance1.
     * @return VO_XXEPortalAttendance1
     */
    public ViewObjectImpl getVO_XXEPortalAttendance1() {
        return (ViewObjectImpl)findViewObject("VO_XXEPortalAttendance1");
    }

    /**
     * Container's getter for VO_SatOpt1.
     * @return VO_SatOpt1
     */
    public ViewObjectImpl getVO_SatOpt1() {
        return (ViewObjectImpl)findViewObject("VO_SatOpt1");
    }

    /**
     * Container's getter for Leave_typeLov1.
     * @return Leave_typeLov1
     */
    public ViewObjectImpl getLeave_typeLov1() {
        return (ViewObjectImpl)findViewObject("Leave_typeLov1");
    }

    /**
     * Container's getter for VO_SATWORKING1.
     * @return VO_SATWORKING1
     */
    public ViewObjectImpl getVO_SATWORKING1() {
        return (ViewObjectImpl)findViewObject("VO_SATWORKING1");
    }

    /**
     * Container's getter for VO_RptLateSitting1.
     * @return VO_RptLateSitting1
     */
    public ViewObjectImpl getVO_RptLateSitting1() {
        return (ViewObjectImpl)findViewObject("VO_RptLateSitting1");
    }

    /**
     * Container's getter for VO_SUNWORKING1.
     * @return VO_SUNWORKING1
     */
    public ViewObjectImpl getVO_SUNWORKING1() {
        return (ViewObjectImpl)findViewObject("VO_SUNWORKING1");
    }

    /**
     * Container's getter for VO_SupervisorOrgChart1.
     * @return VO_SupervisorOrgChart1
     */
    public ViewObjectImpl getVO_SupervisorOrgChart1() {
        return (ViewObjectImpl)findViewObject("VO_SupervisorOrgChart1");
    }

    /**
     * Container's getter for VO_SupervisorOrgChart2.
     * @return VO_SupervisorOrgChart2
     */
    public ViewObjectImpl getVO_SupervisorOrgChart2() {
        return (ViewObjectImpl)findViewObject("VO_SupervisorOrgChart2");
    }

    /**
     * Container's getter for VL_SupervisorORG1.
     * @return VL_SupervisorORG1
     */
    public ViewLinkImpl getVL_SupervisorORG1() {
        return (ViewLinkImpl)findViewLink("VL_SupervisorORG1");
    }

    /**
     * Container's getter for VO_AttendanceHR5.
     * @return VO_AttendanceHR5
     */
    public VO_AttendanceHRImpl getVO_AttendanceHR5() {
        return (VO_AttendanceHRImpl)findViewObject("VO_AttendanceHR5");
    }

    /**
     * Container's getter for VO_ConsumedLeaves3.
     * @return VO_ConsumedLeaves3
     */
    public ViewObjectImpl getVO_ConsumedLeaves3() {
        return (ViewObjectImpl)findViewObject("VO_ConsumedLeaves3");
    }

    /**
     * Container's getter for VL_Atd2ConsumedLeaveds.
     * @return VL_Atd2ConsumedLeaveds
     */
    public ViewLinkImpl getVL_Atd2ConsumedLeaveds() {
        return (ViewLinkImpl)findViewLink("VL_Atd2ConsumedLeaveds");
    }

    /**
     * Container's getter for VO_AttendanceHR6.
     * @return VO_AttendanceHR6
     */
    public VO_AttendanceHRImpl getVO_AttendanceHR6() {
        return (VO_AttendanceHRImpl)findViewObject("VO_AttendanceHR6");
    }

    /**
     * Container's getter for VO_AttendanceIrregularityV2.
     * @return VO_AttendanceIrregularityV2
     */
    public ViewObjectImpl getVO_AttendanceIrregularityV2() {
        return (ViewObjectImpl)findViewObject("VO_AttendanceIrregularityV2");
    }

    /**
     * Container's getter for VL_Atd2Irregularities.
     * @return VL_Atd2Irregularities
     */
    public ViewLinkImpl getVL_Atd2Irregularities() {
        return (ViewLinkImpl)findViewLink("VL_Atd2Irregularities");
    }

    /**
     * Container's getter for VO_EmpIRR1.
     * @return VO_EmpIRR1
     */
    public ViewObjectImpl getVO_EmpIRR1() {
        return (ViewObjectImpl)findViewObject("VO_EmpIRR1");
    }

    /**
     * Container's getter for VO_AttendanceHR7.
     * @return VO_AttendanceHR7
     */
    public VO_AttendanceHRImpl getVO_AttendanceHR7() {
        return (VO_AttendanceHRImpl)findViewObject("VO_AttendanceHR7");
    }

    /**
     * Container's getter for VO_EmpIRR2.
     * @return VO_EmpIRR2
     */
    public ViewObjectImpl getVO_EmpIRR2() {
        return (ViewObjectImpl)findViewObject("VO_EmpIRR2");
    }

    /**
     * Container's getter for VL_AtdIRR.
     * @return VL_AtdIRR
     */
    public ViewLinkImpl getVL_AtdIRR() {
        return (ViewLinkImpl)findViewLink("VL_AtdIRR");
    }

    /**
     * Container's getter for VO_TravellingLeave1.
     * @return VO_TravellingLeave1
     */
    public ViewObjectImpl getVO_TravellingLeave1() {
        return (ViewObjectImpl)findViewObject("VO_TravellingLeave1");
    }

    /**
     * Container's getter for VO_IntercomDir1.
     * @return VO_IntercomDir1
     */
    public ViewObjectImpl getVO_IntercomDir1() {
        return (ViewObjectImpl)findViewObject("VO_IntercomDir1");
    }

    /**
     * Container's getter for IntercomTypeLOV1.
     * @return IntercomTypeLOV1
     */
    public ViewObjectImpl getIntercomTypeLOV1() {
        return (ViewObjectImpl)findViewObject("IntercomTypeLOV1");
    }

    /**
     * Container's getter for VO_RemainingLeaves1.
     * @return VO_RemainingLeaves1
     */
    public ViewObjectImpl getVO_RemainingLeaves1() {
        return (ViewObjectImpl)findViewObject("VO_RemainingLeaves1");
    }

    /**
     * Container's getter for VO_OVERTIME_EMPS1.
     * @return VO_OVERTIME_EMPS1
     */
    public ViewObjectImpl getVO_OVERTIME_EMPS1() {
        return (ViewObjectImpl)findViewObject("VO_OVERTIME_EMPS1");
    }

    /**
     * Container's getter for VO_OVERTIME_EMPS2.
     * @return VO_OVERTIME_EMPS2
     */
    public ViewObjectImpl getVO_OVERTIME_EMPS2() {
        return (ViewObjectImpl)findViewObject("VO_OVERTIME_EMPS2");
    }

    /**
     * Container's getter for VO_OVERTIME_EMPS3.
     * @return VO_OVERTIME_EMPS3
     */
    public ViewObjectImpl getVO_OVERTIME_EMPS3() {
        return (ViewObjectImpl)findViewObject("VO_OVERTIME_EMPS3");
    }

    /**
     * Container's getter for VO_OVERTIME_ATTENDANCE1.
     * @return VO_OVERTIME_ATTENDANCE1
     */
    public ViewObjectImpl getVO_OVERTIME_ATTENDANCE1() {
        return (ViewObjectImpl)findViewObject("VO_OVERTIME_ATTENDANCE1");
    }

    /**
     * Container's getter for VL_OVERTIME.
     * @return VL_OVERTIME
     */
    public ViewLinkImpl getVL_OVERTIME() {
        return (ViewLinkImpl)findViewLink("VL_OVERTIME");
    }

    /**
     * Container's getter for VO_OVERTIME_DETAILS1.
     * @return VO_OVERTIME_DETAILS1
     */
    public ViewObjectImpl getVO_OVERTIME_DETAILS1() {
        return (ViewObjectImpl)findViewObject("VO_OVERTIME_DETAILS1");
    }

    /**
     * Container's getter for VO_OVERTIME_ATTENDANCE2.
     * @return VO_OVERTIME_ATTENDANCE2
     */
    public ViewObjectImpl getVO_OVERTIME_ATTENDANCE2() {
        return (ViewObjectImpl)findViewObject("VO_OVERTIME_ATTENDANCE2");
    }

    /**
     * Container's getter for VO_OVERTIME_DETAILS2.
     * @return VO_OVERTIME_DETAILS2
     */
    public ViewObjectImpl getVO_OVERTIME_DETAILS2() {
        return (ViewObjectImpl)findViewObject("VO_OVERTIME_DETAILS2");
    }

    /**
     * Container's getter for VL_OVERTIME_EMP_DETAILS.
     * @return VL_OVERTIME_EMP_DETAILS
     */
    public ViewLinkImpl getVL_OVERTIME_EMP_DETAILS() {
        return (ViewLinkImpl)findViewLink("VL_OVERTIME_EMP_DETAILS");
    }

    /**
     * Container's getter for VO_ADMIN_IRREGULARITIES1.
     * @return VO_ADMIN_IRREGULARITIES1
     */
    public ViewObjectImpl getVO_ADMIN_IRREGULARITIES1() {
        return (ViewObjectImpl)findViewObject("VO_ADMIN_IRREGULARITIES1");
    }

    /**
     * Container's getter for LOV_EMP1.
     * @return LOV_EMP1
     */
    public ViewObjectImpl getLOV_EMP1() {
        return (ViewObjectImpl)findViewObject("LOV_EMP1");
    }

    /**
     * Container's getter for VO_WAIVEOFFREQ1.
     * @return VO_WAIVEOFFREQ1
     */
    public ViewObjectImpl getVO_WAIVEOFFREQ1() {
        return (ViewObjectImpl)findViewObject("VO_WAIVEOFFREQ1");
    }

    /**
     * Container's getter for LOV_IRRTYPE1.
     * @return LOV_IRRTYPE1
     */
    public ViewObjectImpl getLOV_IRRTYPE1() {
        return (ViewObjectImpl)findViewObject("LOV_IRRTYPE1");
    }

    /**
     * Container's getter for LOV_ATTENDANCE1.
     * @return LOV_ATTENDANCE1
     */
    public ViewObjectImpl getLOV_ATTENDANCE1() {
        return (ViewObjectImpl)findViewObject("LOV_ATTENDANCE1");
    }

    /**
     * Container's getter for VO_PARTTIMES1.
     * @return VO_PARTTIMES1
     */
    public ViewObjectImpl getVO_PARTTIMES1() {
        return (ViewObjectImpl)findViewObject("VO_PARTTIMES1");
    }

    /**
     * Container's getter for VO_AttendanceHR8.
     * @return VO_AttendanceHR8
     */
    public VO_AttendanceHRImpl getVO_AttendanceHR8() {
        return (VO_AttendanceHRImpl)findViewObject("VO_AttendanceHR8");
    }

    /**
     * Container's getter for VO_PARTTIMES2.
     * @return VO_PARTTIMES2
     */
    public ViewObjectImpl getVO_PARTTIMES2() {
        return (ViewObjectImpl)findViewObject("VO_PARTTIMES2");
    }

    /**
     * Container's getter for VL_ATDPARTTIME.
     * @return VL_ATDPARTTIME
     */
    public ViewLinkImpl getVL_ATDPARTTIME() {
        return (ViewLinkImpl)findViewLink("VL_ATDPARTTIME");
    }

    /**
     * Container's getter for VO_Attendance3.
     * @return VO_Attendance3
     */
    public VO_AttendanceImpl getVO_Attendance3() {
        return (VO_AttendanceImpl)findViewObject("VO_Attendance3");
    }

    /**
     * Container's getter for Missed_Minutes_VL.
     * @return Missed_Minutes_VL
     */
    public ViewLinkImpl getMissed_Minutes_VL() {
        return (ViewLinkImpl)findViewLink("Missed_Minutes_VL");
    }


    /**
     * Container's getter for VO_Attendance4.
     * @return VO_Attendance4
     */
    public VO_AttendanceImpl getVO_Attendance4() {
        return (VO_AttendanceImpl)findViewObject("VO_Attendance4");
    }

    /**
     * Container's getter for VO_MISSING_MINUTES3.
     * @return VO_MISSING_MINUTES3
     */
    public VO_MISSING_MINUTESImpl getVO_MISSING_MINUTES3() {
        return (VO_MISSING_MINUTESImpl)findViewObject("VO_MISSING_MINUTES3");
    }

    /**
     * Container's getter for VO_MISSING_MINUTES1.
     * @return VO_MISSING_MINUTES1
     */
    public VO_MISSING_MINUTESImpl getVO_MISSING_MINUTES1() {
        return (VO_MISSING_MINUTESImpl)findViewObject("VO_MISSING_MINUTES1");
    }

    /**
     * Container's getter for Missing_Minutes_VL.
     * @return Missing_Minutes_VL
     */
    public ViewLinkImpl getMissing_Minutes_VL() {
        return (ViewLinkImpl)findViewLink("Missing_Minutes_VL");
    }

    /**
     * Container's getter for VO_MISSING_MINUTES2.
     * @return VO_MISSING_MINUTES2
     */
    public VO_MISSING_MINUTESImpl getVO_MISSING_MINUTES2() {
        return (VO_MISSING_MINUTESImpl)findViewObject("VO_MISSING_MINUTES2");
    }

    /**
     * Container's getter for Missing_Minutes_VL1.
     * @return Missing_Minutes_VL1
     */
    public ViewLinkImpl getMissing_Minutes_VL1() {
        return (ViewLinkImpl)findViewLink("Missing_Minutes_VL1");
    }

    /**
     * Container's getter for VO_Attendance5.
     * @return VO_Attendance5
     */
    public VO_AttendanceImpl getVO_Attendance5() {
        return (VO_AttendanceImpl)findViewObject("VO_Attendance5");
    }

    /**
     * Container's getter for VO_PARTTIMES3.
     * @return VO_PARTTIMES3
     */
    public ViewObjectImpl getVO_PARTTIMES3() {
        return (ViewObjectImpl)findViewObject("VO_PARTTIMES3");
    }

    /**
     * Container's getter for VL_PART_TIMES_ATD.
     * @return VL_PART_TIMES_ATD
     */
    public ViewLinkImpl getVL_PART_TIMES_ATD() {
        return (ViewLinkImpl)findViewLink("VL_PART_TIMES_ATD");
    }

    /**
     * Container's getter for VO_ATTENDANCE_UNPOSTING1.
     * @return VO_ATTENDANCE_UNPOSTING1
     */
    public ViewObjectImpl getVO_ATTENDANCE_UNPOSTING1() {
        return (ViewObjectImpl)findViewObject("VO_ATTENDANCE_UNPOSTING1");
    }
}
