package hub.nishat.net.model.VO;

import hub.nishat.net.model.AM.HubModuleImpl;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.text.SimpleDateFormat;

import java.util.Calendar;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.RowSetIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;

import view.nishat.net.Helper.CommonUtil;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 03 09:47:29 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_AttendanceRowImpl extends ViewRowImpl {


    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        EmpAtdId {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getEmpAtdId();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setEmpAtdId((Number)value);
            }
        }
        ,
        Description {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getDescription();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        EmpId {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getEmpId();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setEmpId((Number)value);
            }
        }
        ,
        EmpName {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getEmpName();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setEmpName((String)value);
            }
        }
        ,
        CardNum {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getCardNum();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setCardNum((String)value);
            }
        }
        ,
        LeaveCancelled {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getLeaveCancelled();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setLeaveCancelled((String)value);
            }
        }
        ,
        ExpectedWorkHours {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getExpectedWorkHours();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setExpectedWorkHours((String)value);
            }
        }
        ,
        MinInTime {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getMinInTime();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setMinInTime((Date)value);
            }
        }
        ,
        MaxOutTime {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getMaxOutTime();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setMaxOutTime((Date)value);
            }
        }
        ,
        PreviousDayOutTime {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getPreviousDayOutTime();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setPreviousDayOutTime((String)value);
            }
        }
        ,
        PreviousDayEffectiveHours {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getPreviousDayEffectiveHours();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setPreviousDayEffectiveHours((String)value);
            }
        }
        ,
        Outtime {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getOuttime();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setOuttime((String)value);
            }
        }
        ,
        Intime {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getIntime();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setIntime((String)value);
            }
        }
        ,
        EffectiveWorkedHours {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getEffectiveWorkedHours();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setEffectiveWorkedHours((String)value);
            }
        }
        ,
        Total {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getTotal();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setTotal((String)value);
            }
        }
        ,
        MaxStartTime {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getMaxStartTime();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setMaxStartTime((String)value);
            }
        }
        ,
        MaxEndTime {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getMaxEndTime();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setMaxEndTime((String)value);
            }
        }
        ,
        EndTime {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getEndTime();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setEndTime((String)value);
            }
        }
        ,
        StartTime {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getStartTime();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setStartTime((String)value);
            }
        }
        ,
        AttendanceDate {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getAttendanceDate();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setAttendanceDate((Date)value);
            }
        }
        ,
        LeaveTypeId {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getLeaveTypeId();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setLeaveTypeId((Number)value);
            }
        }
        ,
        LeaveApprovedFlag {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getLeaveApprovedFlag();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setLeaveApprovedFlag((String)value);
            }
        }
        ,
        TypeOfLeave {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getTypeOfLeave();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setTypeOfLeave((Number)value);
            }
        }
        ,
        PolicyException {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getPolicyException();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setPolicyException((String)value);
            }
        }
        ,
        LeaveToday {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getLeaveToday();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setLeaveToday((String)value);
            }
        }
        ,
        IsHalf {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getIsHalf();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setIsHalf((String)value);
            }
        }
        ,
        WorkingTime {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getWorkingTime();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setWorkingTime((String)value);
            }
        }
        ,
        LeaveType {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getLeaveType();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setLeaveType((String)value);
            }
        }
        ,
        PolicyExceptionApprovedFlag {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getPolicyExceptionApprovedFlag();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setPolicyExceptionApprovedFlag((String)value);
            }
        }
        ,
        LateSittingMinTiming {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getLateSittingMinTiming();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setLateSittingMinTiming((String)value);
            }
        }
        ,
        Day {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getDay();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setDay((String)value);
            }
        }
        ,
        Today {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getToday();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setToday((String)value);
            }
        }
        ,
        Month {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getMonth();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setMonth((String)value);
            }
        }
        ,
        MonthNumber {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getMonthNumber();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setMonthNumber((Number)value);
            }
        }
        ,
        Year {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getYear();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setYear((String)value);
            }
        }
        ,
        OffDayWorking {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getOffDayWorking();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setOffDayWorking((String)value);
            }
        }
        ,
        EmpType {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getEmpType();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setEmpType((Number)value);
            }
        }
        ,
        LateIn {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getLateIn();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setLateIn((String)value);
            }
        }
        ,
        EarlyOut {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getEarlyOut();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setEarlyOut((String)value);
            }
        }
        ,
        DayStatus {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getDayStatus();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setDayStatus((String)value);
            }
        }
        ,
        Sysdate {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getSysdate();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setSysdate((String)value);
            }
        }
        ,
        off_day_working_bool {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getoff_day_working_bool();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setoff_day_working_bool((Boolean)value);
            }
        }
        ,
        saturdayOrHoliday {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getsaturdayOrHoliday();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setsaturdayOrHoliday((String)value);
            }
        }
        ,
        isSunday {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getisSunday();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setisSunday((String)value);
            }
        }
        ,
        isLeave {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getisLeave();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setisLeave((String)value);
            }
        }
        ,
        HoursMissing {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getHoursMissing();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setHoursMissing((String)value);
            }
        }
        ,
        VO_AttendanceEvents {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getVO_AttendanceEvents();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        VO_MISSING_MINUTES {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getVO_MISSING_MINUTES();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        VO_Months1 {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getVO_Months1();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        VO_Years1 {
            public Object get(VO_AttendanceRowImpl obj) {
                return obj.getVO_Years1();
            }

            public void put(VO_AttendanceRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(VO_AttendanceRowImpl object);

        public abstract void put(VO_AttendanceRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EMPATDID = AttributesEnum.EmpAtdId.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int EMPID = AttributesEnum.EmpId.index();
    public static final int EMPNAME = AttributesEnum.EmpName.index();
    public static final int CARDNUM = AttributesEnum.CardNum.index();
    public static final int LEAVECANCELLED = AttributesEnum.LeaveCancelled.index();
    public static final int EXPECTEDWORKHOURS = AttributesEnum.ExpectedWorkHours.index();
    public static final int MININTIME = AttributesEnum.MinInTime.index();
    public static final int MAXOUTTIME = AttributesEnum.MaxOutTime.index();
    public static final int PREVIOUSDAYOUTTIME = AttributesEnum.PreviousDayOutTime.index();
    public static final int PREVIOUSDAYEFFECTIVEHOURS = AttributesEnum.PreviousDayEffectiveHours.index();
    public static final int OUTTIME = AttributesEnum.Outtime.index();
    public static final int INTIME = AttributesEnum.Intime.index();
    public static final int EFFECTIVEWORKEDHOURS = AttributesEnum.EffectiveWorkedHours.index();
    public static final int TOTAL = AttributesEnum.Total.index();
    public static final int MAXSTARTTIME = AttributesEnum.MaxStartTime.index();
    public static final int MAXENDTIME = AttributesEnum.MaxEndTime.index();
    public static final int ENDTIME = AttributesEnum.EndTime.index();
    public static final int STARTTIME = AttributesEnum.StartTime.index();
    public static final int ATTENDANCEDATE = AttributesEnum.AttendanceDate.index();
    public static final int LEAVETYPEID = AttributesEnum.LeaveTypeId.index();
    public static final int LEAVEAPPROVEDFLAG = AttributesEnum.LeaveApprovedFlag.index();
    public static final int TYPEOFLEAVE = AttributesEnum.TypeOfLeave.index();
    public static final int POLICYEXCEPTION = AttributesEnum.PolicyException.index();
    public static final int LEAVETODAY = AttributesEnum.LeaveToday.index();
    public static final int ISHALF = AttributesEnum.IsHalf.index();
    public static final int WORKINGTIME = AttributesEnum.WorkingTime.index();
    public static final int LEAVETYPE = AttributesEnum.LeaveType.index();
    public static final int POLICYEXCEPTIONAPPROVEDFLAG = AttributesEnum.PolicyExceptionApprovedFlag.index();
    public static final int LATESITTINGMINTIMING = AttributesEnum.LateSittingMinTiming.index();
    public static final int DAY = AttributesEnum.Day.index();
    public static final int TODAY = AttributesEnum.Today.index();
    public static final int MONTH = AttributesEnum.Month.index();
    public static final int MONTHNUMBER = AttributesEnum.MonthNumber.index();
    public static final int YEAR = AttributesEnum.Year.index();
    public static final int OFFDAYWORKING = AttributesEnum.OffDayWorking.index();
    public static final int EMPTYPE = AttributesEnum.EmpType.index();
    public static final int LATEIN = AttributesEnum.LateIn.index();
    public static final int EARLYOUT = AttributesEnum.EarlyOut.index();
    public static final int DAYSTATUS = AttributesEnum.DayStatus.index();
    public static final int SYSDATE = AttributesEnum.Sysdate.index();
    public static final int OFF_DAY_WORKING_BOOL = AttributesEnum.off_day_working_bool.index();
    public static final int SATURDAYORHOLIDAY = AttributesEnum.saturdayOrHoliday.index();
    public static final int ISSUNDAY = AttributesEnum.isSunday.index();
    public static final int ISLEAVE = AttributesEnum.isLeave.index();
    public static final int HOURSMISSING = AttributesEnum.HoursMissing.index();
    public static final int VO_ATTENDANCEEVENTS = AttributesEnum.VO_AttendanceEvents.index();
    public static final int VO_MISSING_MINUTES = AttributesEnum.VO_MISSING_MINUTES.index();
    public static final int VO_MONTHS1 = AttributesEnum.VO_Months1.index();
    public static final int VO_YEARS1 = AttributesEnum.VO_Years1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public VO_AttendanceRowImpl() {
    }

    /**
     * Gets EO_Attendance entity object.
     * @return the EO_Attendance
     */
    public EntityImpl getEO_Attendance() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for EMP_ATD_ID using the alias name EmpAtdId.
     * @return the EMP_ATD_ID
     */
    public Number getEmpAtdId() {
        return (Number)getAttributeInternal(EMPATDID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_ATD_ID using the alias name EmpAtdId.
     * @param value value to set the EMP_ATD_ID
     */
    public void setEmpAtdId(Number value) {
        setAttributeInternal(EMPATDID, value);
    }


    /**
     * Gets the attribute value for the calculated attribute Description.
     * @return the Description
     */
    public String getDescription() {
        return (String)getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Description.
     * @param value value to set the  Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for EMP_ID using the alias name EmpId.
     * @return the EMP_ID
     */
    public Number getEmpId() {
        return (Number)getAttributeInternal(EMPID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_ID using the alias name EmpId.
     * @param value value to set the EMP_ID
     */
    public void setEmpId(Number value) {
        setAttributeInternal(EMPID, value);
    }

    /**
     * Gets the attribute value for EMP_NAME using the alias name EmpName.
     * @return the EMP_NAME
     */
    public String getEmpName() {
        return (String)getAttributeInternal(EMPNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_NAME using the alias name EmpName.
     * @param value value to set the EMP_NAME
     */
    public void setEmpName(String value) {
        setAttributeInternal(EMPNAME, value);
    }

    /**
     * Gets the attribute value for CARD_NUM using the alias name CardNum.
     * @return the CARD_NUM
     */
    public String getCardNum() {
        return (String)getAttributeInternal(CARDNUM);
    }

    /**
     * Sets <code>value</code> as attribute value for CARD_NUM using the alias name CardNum.
     * @param value value to set the CARD_NUM
     */
    public void setCardNum(String value) {
        setAttributeInternal(CARDNUM, value);
    }

    /**
     * Gets the attribute value for EXPECTED_WORK_HOURS using the alias name ExpectedWorkHours.
     * @return the EXPECTED_WORK_HOURS
     */
    public String getExpectedWorkHours() {
        return (String)getAttributeInternal(EXPECTEDWORKHOURS);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPECTED_WORK_HOURS using the alias name ExpectedWorkHours.
     * @param value value to set the EXPECTED_WORK_HOURS
     */
    public void setExpectedWorkHours(String value) {
        setAttributeInternal(EXPECTEDWORKHOURS, value);
    }

    /**
     * Gets the attribute value for MIN_IN_TIME using the alias name MinInTime.
     * @return the MIN_IN_TIME
     */
    public Date getMinInTime() {
        return (Date)getAttributeInternal(MININTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for MIN_IN_TIME using the alias name MinInTime.
     * @param value value to set the MIN_IN_TIME
     */
    public void setMinInTime(Date value) {
        setAttributeInternal(MININTIME, value);
    }

    /**
     * Gets the attribute value for MAX_OUT_TIME using the alias name MaxOutTime.
     * @return the MAX_OUT_TIME
     */
    public Date getMaxOutTime() {
        return (Date)getAttributeInternal(MAXOUTTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for MAX_OUT_TIME using the alias name MaxOutTime.
     * @param value value to set the MAX_OUT_TIME
     */
    public void setMaxOutTime(Date value) {
        setAttributeInternal(MAXOUTTIME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PreviousDayOutTime.
     * @return the PreviousDayOutTime
     */
    public String getPreviousDayOutTime() {
        return (String)getAttributeInternal(PREVIOUSDAYOUTTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PreviousDayOutTime.
     * @param value value to set the  PreviousDayOutTime
     */
    public void setPreviousDayOutTime(String value) {
        setAttributeInternal(PREVIOUSDAYOUTTIME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PreviousDayEffectiveHours.
     * @return the PreviousDayEffectiveHours
     */
    public String getPreviousDayEffectiveHours() {
        return (String)getAttributeInternal(PREVIOUSDAYEFFECTIVEHOURS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PreviousDayEffectiveHours.
     * @param value value to set the  PreviousDayEffectiveHours
     */
    public void setPreviousDayEffectiveHours(String value) {
        setAttributeInternal(PREVIOUSDAYEFFECTIVEHOURS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Outtime.
     * @return the Outtime
     */
    public String getOuttime() {
        return (String)getAttributeInternal(OUTTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Outtime.
     * @param value value to set the  Outtime
     */
    public void setOuttime(String value) {
        setAttributeInternal(OUTTIME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Intime.
     * @return the Intime
     */
    public String getIntime() {
        return (String)getAttributeInternal(INTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Intime.
     * @param value value to set the  Intime
     */
    public void setIntime(String value) {
        setAttributeInternal(INTIME, value);
    }

    /**
     * Gets the attribute value for EFFECTIVE_WORKED_HOURS using the alias name EffectiveWorkedHours.
     * @return the EFFECTIVE_WORKED_HOURS
     */
    public String getEffectiveWorkedHours() {
        return (String)getAttributeInternal(EFFECTIVEWORKEDHOURS);
    }

    public void deductLeave(String leaveType) {
       
    }

    

    

    /**
     * Sets <code>value</code> as attribute value for EFFECTIVE_WORKED_HOURS using the alias name EffectiveWorkedHours.
     * @param value value to set the EFFECTIVE_WORKED_HOURS
     */
    public void setEffectiveWorkedHours(String value) {
        setAttributeInternal(EFFECTIVEWORKEDHOURS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Total.
     * @return the Total
     */
    public String getTotal() {
        String time = (String) getAttributeInternal(TOTAL);
        if (time!=null)
        {
//            CommonUtil.showMessage(time_num+"", 112);
//            return time_num+"";
             int time_num = Integer.parseInt(time.split(":")[0]);
            if (time_num > 7) return "08:00";
            else return time;
        }
        else return null;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Total.
     * @param value value to set the  Total
     */
    public void setTotal(String value) {
        setAttributeInternal(TOTAL, value);
    }

    /**
     * Gets the attribute value for MAX_START_TIME using the alias name MaxStartTime.
     * @return the MAX_START_TIME
     */
    public String getMaxStartTime() {
        return (String)getAttributeInternal(MAXSTARTTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for MAX_START_TIME using the alias name MaxStartTime.
     * @param value value to set the MAX_START_TIME
     */
    public void setMaxStartTime(String value) {
        setAttributeInternal(MAXSTARTTIME, value);
    }

    /**
     * Gets the attribute value for MAX_END_TIME using the alias name MaxEndTime.
     * @return the MAX_END_TIME
     */
    public String getMaxEndTime() {
        return (String)getAttributeInternal(MAXENDTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for MAX_END_TIME using the alias name MaxEndTime.
     * @param value value to set the MAX_END_TIME
     */
    public void setMaxEndTime(String value) {
        setAttributeInternal(MAXENDTIME, value);
    }

    /**
     * Gets the attribute value for END_TIME using the alias name EndTime.
     * @return the END_TIME
     */
    public String getEndTime() {
        return (String)getAttributeInternal(ENDTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for END_TIME using the alias name EndTime.
     * @param value value to set the END_TIME
     */
    public void setEndTime(String value) {
        setAttributeInternal(ENDTIME, value);
    }

    /**
     * Gets the attribute value for START_TIME using the alias name StartTime.
     * @return the START_TIME
     */
    public String getStartTime() {
        return (String)getAttributeInternal(STARTTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for START_TIME using the alias name StartTime.
     * @param value value to set the START_TIME
     */
    public void setStartTime(String value) {
        setAttributeInternal(STARTTIME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Day.
     * @return the Day
     */
    public String getDay() {
        return (String)getAttributeInternal(DAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Day.
     * @param value value to set the  Day
     */
    public void setDay(String value) {
        setAttributeInternal(DAY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Today.
     * @return the Today
     */
    public String getToday() {
        return (String)getAttributeInternal(TODAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Today.
     * @param value value to set the  Today
     */
    public void setToday(String value) {
        setAttributeInternal(TODAY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Month.
     * @return the Month
     */
    public String getMonth() {
        return (String)getAttributeInternal(MONTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Month.
     * @param value value to set the  Month
     */
    public void setMonth(String value) {
        setAttributeInternal(MONTH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MonthNumber.
     * @return the MonthNumber
     */
    public Number getMonthNumber() {
        return (Number) getAttributeInternal(MONTHNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MonthNumber.
     * @param value value to set the  MonthNumber
     */
    public void setMonthNumber(Number value) {
        setAttributeInternal(MONTHNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Year.
     * @return the Year
     */
    public String getYear() {
        return (String)getAttributeInternal(YEAR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Year.
     * @param value value to set the  Year
     */
    public void setYear(String value) {
        setAttributeInternal(YEAR, value);
    }


    /**
     * Gets the attribute value for the calculated attribute LateIn.
     * @return the LateIn
     */
    public String getLateIn() {
        String status = "";
        int lateSittingMins = 0;
        String maxInFlexi = getMaxStartTime();
        Date dMinIntime = getMinInTime();
        String workAfterOfficeTimings = "";
        String previousDayOutTime =
            getPreviousDayOutTime() != null ? getPreviousDayOutTime().toString():
            null;
        if (dMinIntime != null) {
            String amPmString =
                getMinInTime().getValue().toLocaleString().split(" ")[4];
            String timeString =
                getMinInTime().getValue().toLocaleString().split(",")[1];
            String timeStringWithAmPm =
                (timeString.split(":")[0] + ":" + timeString.split(":")[1] +
                 " " + amPmString).trim();
            String minInTime =
                timeStringWithAmPm.split(" ")[1] + " " + timeStringWithAmPm.split(" ")[2];

            String maxInFlexiC = "";
            if (previousDayOutTime != null) {
                workAfterOfficeTimings =
                        CommonUtil.subtractTime("6:30 PM", getPreviousDayOutTime()).replace("#",
                                                                                            ":");
                //                System.out.println("Out Time: "+getPreviousDayOutTime());
                //                System.out.println("work after office timings: "+workAfterOfficeTimings);
                lateSittingMins =
                    Integer.parseInt(workAfterOfficeTimings.split(":")[0]) *
                    60 +
                    Integer.parseInt(workAfterOfficeTimings.split(":")[1]);
                //System.out.println("Late sitting mins: "+lateSittingMins+" - "+getAttendanceDate().toString());
                if (lateSittingMins >= 60 && lateSittingMins <= 149) {
                    maxInFlexiC = "10:30 AM";
                    //System.out.println(" from 10:30 AM");
                } else if (lateSittingMins >= 149 && lateSittingMins <= 209) {
                    maxInFlexiC = "11:00 AM";
                    
                    //System.out.println(" from 11:00 AM");
                } else if (lateSittingMins > 209) {
                    maxInFlexiC = "11:30 AM";
                    //System.out.println(" from 11:30 AM");
                } else {
                    maxInFlexiC = maxInFlexi;
                }
                status = maxInFlexiC;
                

            } else {
                maxInFlexiC = maxInFlexi;
            }
            String lateIn =
                CommonUtil.limitSubtractTime(maxInFlexiC, minInTime,getExpectedWorkHours()); //minInTime - maxInFlexi+someFigure
            
            //System.out.println("AttendanceRow.java: "+lateIn);
            
            return lateIn.replace("#", ":");
            //return minInTime +" - "+status+" ( "+lateSittingMins+")";
        } else {
            return null;
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LateIn.
     * @param value value to set the  LateIn
     */
    public void setLateIn(String value) {
        setAttributeInternal(LATEIN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EarlyOut.
     * @return the EarlyOut
     */
    public String getEarlyOut() {
        if (getMaxOutTime() != null) {
                    //String intime = "07:59 AM";
//                    String startTime = "8:30 AM";
//                    String maxStartTime = "10:00 AM";
                    //String outtime = "07:59 AM";
//                    String maxEndtime = "6:00 PM";
//                    String endTime = "4:30 PM";

            String intime = getIntime();
            String startTime = getStartTime();
            String outtime = getOuttime();
            String maxEndtime = getMaxEndTime();
            String maxStartTime = getMaxStartTime();
            String endTime = getEndTime();
            String expectedHours = getExpectedWorkHours();

            String diff_intime_and_startTime =
                CommonUtil.subtractTime(intime, startTime);
            String diff_intime_and_maxStartTime =
                CommonUtil.subtractTime(intime, maxStartTime);
            String diff_intime_and_maxEndTime =
                CommonUtil.subtractTime(intime, maxEndtime);

            int min_diff_intime_and_startTime =
                Integer.parseInt(diff_intime_and_startTime.replace("#",
                                                                   ":").split(":")[0]) +
                Integer.parseInt(diff_intime_and_startTime.replace("#",
                                                                   ":").split(":")[1]);
            int min_diff_intime_and_maxStartTime =
                Integer.parseInt(diff_intime_and_maxStartTime.replace("#",
                                                                      ":").split(":")[0]) +
                Integer.parseInt(diff_intime_and_maxStartTime.replace("#",
                                                                      ":").split(":")[1]);
            int min_diff_intime_and_maxEndTime =
                Integer.parseInt(diff_intime_and_maxEndTime.replace("#",
                                                                    ":").split(":")[0]) +
                Integer.parseInt(diff_intime_and_maxEndTime.replace("#",
                                                                    ":").split(":")[1]);
            
            //CommonUtil.log("difference: "+min_diff_intime_and_startTime+" "+intime+" - "+startTime);


            String earlyOut = null;
            if (min_diff_intime_and_maxEndTime < 0) {
                earlyOut = "0:00";
            } else {
                if (min_diff_intime_and_startTime <= 0 &&
                    min_diff_intime_and_maxStartTime >= 0) {
//                    System.out.println("Case#1 "+CommonUtil.addHourToAmPMTime(intime.split(" ")[0],
//                                                                              "6:30") +
//                                       " - " + outtime);
                    earlyOut =
                            CommonUtil.limitSubtractTime(outtime, CommonUtil.addHourToAmPMTime(intime.split(" ")[0],expectedHours) +" PM",getExpectedWorkHours());
                    //CommonUtil.log("Early outttttttt "+ earlyOut);
                } else if (min_diff_intime_and_startTime > 0) {
                    //System.out.println("Case#2 "+endTime + " - " + outtime);
                    earlyOut = CommonUtil.limitSubtractTime(outtime, endTime,getExpectedWorkHours());
                } else if (min_diff_intime_and_maxStartTime < 0) {
                    //System.out.println("Case#3 "+maxEndtime + " - " + outtime);
                    earlyOut =
                            CommonUtil.limitSubtractTime(outtime, maxEndtime,getExpectedWorkHours());
                }
            }
            
            return earlyOut.replace("#", ":");
        } else {
            return null;
        }


        //        String maxEndFlexi = getMaxEndTime();
        //        Date dMaxOutTime = getMaxOutTime();

        //        if (dMaxOutTime != null) {
        //

        //            String intime = getIntime();
        //            String startTime = getStartTime();
        //            String outtime = getOuttime();
        //            String maxEndtime = getMaxEndTime();
        //            String maxStartTime = getMaxStartTime();
        //            String endTime = getEndTime();
        //                                            String intime = "8:27 AM";
        //                                    String startTime = "8:30 AM";
        //                                    String maxStartTime = "9:30 AM";
        //                                    String outtime = "8:27 AM";
        //                                    String maxEndtime = "5:30 PM";
        //                                    String endTime = "4:30 PM";
        //
        //
        //            boolean flexi =
        //                Integer.parseInt(CommonUtil.subtractTime(startTime, maxEndtime).split("#")[0]) >
        //                8 ? true : false;
        //            //            System.out.println("Time: " +
        //            //                               CommonUtil.subtractTime(startTime, maxEndtime));
        //
        //            //IF IN TIME IS GREATER THEN MIN START TIME OF FLEXI THE inTime = IN TIME
        //            //ELSE IN TIME = START TIME
        //            String inTimeDiff = CommonUtil.subtractTime(intime, startTime);
        //
        //            String inTime =
        //                (Integer.parseInt(inTimeDiff.split("#")[0]) * 60) + Integer.parseInt(inTimeDiff.split("#")[1]) <
        //                0 ? intime : startTime;
        //
        //            //IF OUT TIME IS GREATER THEN MAX END TIME THEN outTime = MAX END TIME
        //            //END outTime = END TIME
        //
        //            String outTimeDiff = CommonUtil.subtractTime(outtime, maxEndtime);
        //            String outTime =
        //                ((Integer.parseInt(outTimeDiff.split("#")[0]) * 60) +
        //                 Integer.parseInt(outTimeDiff.split("#")[0])) < 0 ?
        //                maxEndtime : outtime;
        //
        //            //ATTENDANCE TIME DIFFERENCE
        //            String attTimeDiff = CommonUtil.subtractTime(inTime, outTime);
        //
        //            //IF ATTENDANCE TIME DIFFERENCE IS LESS THEN 8 THEN
        //            //WE WILL CALCULATE EARLY OUT ON THE BASIS OF HIS IN TIME
        //            //ELSE, HE DOES NOT HAS ANY EARLY OUT
        //            if (Integer.parseInt(attTimeDiff.split("#")[0]) * 60 +
        //                Integer.parseInt(attTimeDiff.split("#")[1]) < 8 * 60) {
        //                //NOW CHECK THE IN TIME
        //                String diffIntoMaxStartTime =
        //                    CommonUtil.subtractTime(intime, maxStartTime);
        //                //IF IN TIME IS GREATER THEN MAX START TIME THEN COUNT EARLY OUT FROM MAX OUT TIME
        //                //COUNT EARLY OUT FROM OUT TIME
        //                String early =
        //                    (Integer.parseInt(diffIntoMaxStartTime.split("#")[0]) *
        //                     60) +
        //                    (Integer.parseInt(diffIntoMaxStartTime.split("#")[1])) <=
        //                    0 ? CommonUtil.limitSubtractTime(outTime, maxEndtime)+"?" :
        //                    CommonUtil.limitSubtractTime(outTime, endTime)+" : ";
        //                System.out.println(outTime+ " - "+endTime);
        //
        //                return early.replace("#", ":");
        //            } else {
        //                return "0:0";
        //            }
        //        } else {
        //            return null;
        //        }


    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EarlyOut.
     * @param value value to set the  EarlyOut
     */
    public void setEarlyOut(String value) {
        setAttributeInternal(EARLYOUT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DayStatus.
     * @return the DayStatus
     */
    public String getDayStatus() {
        StringBuilder dayStatus = new StringBuilder();
        dayStatus.append(getDescription() == null ? "" :
                         getDescription().equals("SATURDAY_OFF") ?
                         "Saturday Off" : "");
        return dayStatus.toString();
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DayStatus.
     * @param value value to set the  DayStatus
     */
    public void setDayStatus(String value) {
        setAttributeInternal(DAYSTATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Sysdate.
     * @return the Sysdate
     */
    public String getSysdate() {
        Calendar c = Calendar.getInstance();
        java.util.Date d = c.getTime();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return sdf.format(d);

    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Sysdate.
     * @param value value to set the  Sysdate
     */
    public void setSysdate(String value) {
        setAttributeInternal(SYSDATE, value);
    }


    /**
     * Gets the attribute value for OFF_DAY_WORKING using the alias name OffDayWorking.
     * @return the OFF_DAY_WORKING
     */
    public String getOffDayWorking() {
        return (String)getAttributeInternal(OFFDAYWORKING);
    }

    /**
     * Sets <code>value</code> as attribute value for OFF_DAY_WORKING using the alias name OffDayWorking.
     * @param value value to set the OFF_DAY_WORKING
     */
    public void setOffDayWorking(String value) {
        setAttributeInternal(OFFDAYWORKING, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EmpType.
     * @return the EmpType
     */
    public Number getEmpType() {
        return (Number) getAttributeInternal(EMPTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EmpType.
     * @param value value to set the  EmpType
     */
    public void setEmpType(Number value) {
        setAttributeInternal(EMPTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute off_day_working_bool.
     * @return the off_day_working_bool
     */
    public Boolean getoff_day_working_bool() {
        boolean offDay = false;
        if (getOffDayWorking() == null) {
            offDay = false;
        } else if (getOffDayWorking().equals("Y")) {
            offDay = true;
        }
        return offDay;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute off_day_working_bool.
     * @param value value to set the  off_day_working_bool
     */
    public void setoff_day_working_bool(Boolean value) {
        if (value) {
            setOffDayWorking("Y");
        } else if (!value) {
            setOffDayWorking(null);
        }
    }


    /**
     * Gets the attribute value for the calculated attribute saturdayOrHoliday.
     * @return the saturdayOrHoliday
     */
    public String getsaturdayOrHoliday() {
        String saturdayOrHoliday =
            getDescription() == null ? "" : getDescription().equals("SATURDAY_OFF") ?
                                            "Saturday Off" :
                                            getDescription().equals("SATURDAY_ON") ?
                                            "" : getDescription();
        return saturdayOrHoliday;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute saturdayOrHoliday.
     * @param value value to set the  saturdayOrHoliday
     */
    public void setsaturdayOrHoliday(String value) {
        setAttributeInternal(SATURDAYORHOLIDAY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute isSunday.
     * @return the isSunday
     */
    public String getisSunday() {
        String sunday = getDay().equals("SUNDAY") ? "Sunday Off" : "";
        return sunday;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute isSunday.
     * @param value value to set the  isSunday
     */
    public void setisSunday(String value) {
        setAttributeInternal(ISSUNDAY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute isLeave.
     * @return the isLeave
     */
    public String getisLeave() {
        String leave =
            getLeaveToday() == null ? null : getLeaveToday().equals("Y") ?
                                           getTypeOfLeave().equals("1") ?
                                           "Casual Leave" :
                                           getTypeOfLeave().equals("2") ?
                                           "Annual Leave" : "" : "";
        return leave;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute isLeave.
     * @param value value to set the  isLeave
     */
    public void setisLeave(String value) {
        setAttributeInternal(ISLEAVE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute HoursMissing.
     * @return the HoursMissing
     */
    public String getHoursMissing() {
        if (getEffectiveWorkedHours() != null) {
            int workedMinutes = (Integer.parseInt( getEffectiveWorkedHours().split(":")[0])*60)+
                Integer.parseInt( getEffectiveWorkedHours().split(":")[1]);

            int expectedMinutes = (Integer.parseInt(getExpectedWorkHours().toString().split(":")[0])*60)+
                                  Integer.parseInt(getWorkingTime().split(":")[1]);
        
            int missingMinutes = (expectedMinutes - workedMinutes)<0?0:(expectedMinutes - workedMinutes);
            return missingMinutes+"";
        }else{
            //EMPLOYEE HASN'T DONE ANYTHING ON THIS DAY
            return null;
        }
            
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute HoursMissing.
     * @param value value to set the  HoursMissing
     */
    public void setHoursMissing(String value) {
        setAttributeInternal(HOURSMISSING, value);
    }

    /**
     * Gets the attribute value for LEAVE_CANCELLED using the alias name LeaveCancelled.
     * @return the LEAVE_CANCELLED
     */
    public String getLeaveCancelled() {
        return (String) getAttributeInternal(LEAVECANCELLED);
    }

    /**
     * Sets <code>value</code> as attribute value for LEAVE_CANCELLED using the alias name LeaveCancelled.
     * @param value value to set the LEAVE_CANCELLED
     */
    public void setLeaveCancelled(String value) {
        setAttributeInternal(LEAVECANCELLED, value);
    }

    /**
     * Gets the attribute value for TYPE_OF_LEAVE using the alias name TypeOfLeave.
     * @return the TYPE_OF_LEAVE
     */
    public Number getTypeOfLeave() {
        return (Number)getAttributeInternal(TYPEOFLEAVE);
    }

    /**
     * Sets <code>value</code> as attribute value for TYPE_OF_LEAVE using the alias name TypeOfLeave.
     * @param value value to set the TYPE_OF_LEAVE
     */
    public void setTypeOfLeave(Number value) {
        setAttributeInternal(TYPEOFLEAVE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link VO_AttendanceEvents.
     */
    public RowIterator getVO_AttendanceEvents() {
        return (RowIterator)getAttributeInternal(VO_ATTENDANCEEVENTS);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link VO_MISSING_MINUTES.
     */
    public RowIterator getVO_MISSING_MINUTES() {
        return (RowIterator)getAttributeInternal(VO_MISSING_MINUTES);
    }

    /**
     * Gets the attribute value for LEAVE_TODAY using the alias name LeaveToday.
     * @return the LEAVE_TODAY
     */
    public String getLeaveToday() {
        return (String)getAttributeInternal(LEAVETODAY);
    }

    /**
     * Sets <code>value</code> as attribute value for LEAVE_TODAY using the alias name LeaveToday.
     * @param value value to set the LEAVE_TODAY
     */
    public void setLeaveToday(String value) {
        setAttributeInternal(LEAVETODAY, value);
    }

    /**
     * Gets the attribute value for IS_HALF using the alias name IsHalf.
     * @return the IS_HALF
     */
    public String getIsHalf() {
        return (String)getAttributeInternal(ISHALF);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_HALF using the alias name IsHalf.
     * @param value value to set the IS_HALF
     */
    public void setIsHalf(String value) {
        setAttributeInternal(ISHALF, value);
    }


    /**
     * Gets the attribute value for the calculated attribute WorkingTime.
     * @return the WorkingTime
     */
    public String getWorkingTime() {
        return (String) getAttributeInternal(WORKINGTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WorkingTime.
     * @param value value to set the  WorkingTime
     */
    public void setWorkingTime(String value) {
        setAttributeInternal(WORKINGTIME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LeaveType.
     * @return the LeaveType
     */
    public String getLeaveType() {
        return (String)getAttributeInternal(LEAVETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LeaveType.
     * @param value value to set the  LeaveType
     */
    public void setLeaveType(String value) {
        setAttributeInternal(LEAVETYPE, value);
    }

    /**
     * Gets the attribute value for POLICY_EXCEPTION_APPROVED_FLAG using the alias name PolicyExceptionApprovedFlag.
     * @return the POLICY_EXCEPTION_APPROVED_FLAG
     */
    public String getPolicyExceptionApprovedFlag() {
        return (String)getAttributeInternal(POLICYEXCEPTIONAPPROVEDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for POLICY_EXCEPTION_APPROVED_FLAG using the alias name PolicyExceptionApprovedFlag.
     * @param value value to set the POLICY_EXCEPTION_APPROVED_FLAG
     */
    public void setPolicyExceptionApprovedFlag(String value) {
        setAttributeInternal(POLICYEXCEPTIONAPPROVEDFLAG, value);
    }

    /**
     * Gets the attribute value for POLICY_EXCEPTION using the alias name PolicyException.
     * @return the POLICY_EXCEPTION
     */
    public String getPolicyException() {
        return (String)getAttributeInternal(POLICYEXCEPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for POLICY_EXCEPTION using the alias name PolicyException.
     * @param value value to set the POLICY_EXCEPTION
     */
    public void setPolicyException(String value) {
        setAttributeInternal(POLICYEXCEPTION, value);
    }

    /**
     * Gets the attribute value for LEAVE_TYPE_ID using the alias name LeaveTypeId.
     * @return the LEAVE_TYPE_ID
     */
    public Number getLeaveTypeId() {
        return (Number)getAttributeInternal(LEAVETYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LEAVE_TYPE_ID using the alias name LeaveTypeId.
     * @param value value to set the LEAVE_TYPE_ID
     */
    public void setLeaveTypeId(Number value) {
        setAttributeInternal(LEAVETYPEID, value);
    }

    /**
     * Gets the attribute value for LEAVE_APPROVED_FLAG using the alias name LeaveApprovedFlag.
     * @return the LEAVE_APPROVED_FLAG
     */
    public String getLeaveApprovedFlag() {
        return (String)getAttributeInternal(LEAVEAPPROVEDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for LEAVE_APPROVED_FLAG using the alias name LeaveApprovedFlag.
     * @param value value to set the LEAVE_APPROVED_FLAG
     */
    public void setLeaveApprovedFlag(String value) {
        setAttributeInternal(LEAVEAPPROVEDFLAG, value);
    }


    /**
     * Gets the attribute value for ATTENDANCE_DATE using the alias name AttendanceDate.
     * @return the ATTENDANCE_DATE
     */
    public Date getAttendanceDate() {
        return (Date)getAttributeInternal(ATTENDANCEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTENDANCE_DATE using the alias name AttendanceDate.
     * @param value value to set the ATTENDANCE_DATE
     */
    public void setAttendanceDate(Date value) {
        setAttributeInternal(ATTENDANCEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LateSittingMinTiming.
     * @return the LateSittingMinTiming
     */
    public String getLateSittingMinTiming() {
        return (String)getAttributeInternal(LATESITTINGMINTIMING);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LateSittingMinTiming.
     * @param value value to set the  LateSittingMinTiming
     */
    public void setLateSittingMinTiming(String value) {
        setAttributeInternal(LATESITTINGMINTIMING, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_Months1.
     */
    public RowSet getVO_Months1() {
        return (RowSet)getAttributeInternal(VO_MONTHS1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VO_Years1.
     */
    public RowSet getVO_Years1() {
        return (RowSet)getAttributeInternal(VO_YEARS1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
