package hub.nishat.net.model.VO;

import java.text.DateFormatSymbols;

import java.util.Calendar;

import oracle.jbo.server.ViewObjectImpl;

import view.nishat.net.Helper.CommonUtil;
import view.nishat.net.Helper.Constants;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 07 10:48:49 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_AttendanceImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public VO_AttendanceImpl() {
    }


    /**
     * Returns the variable value for bv_month.
     * @return variable value for bv_month
     */
    public String getbv_month() {
        DateFormatSymbols dfs = new DateFormatSymbols();
        String months[] = dfs.getShortMonths();
        Calendar c = Calendar.getInstance();
        int monthNumber = c.get(Calendar.MONTH);
        return months[monthNumber].toUpperCase();
        //return "APR";
    }

    /**
     * Sets <code>value</code> for variable bv_month.
     * @param value value to bind as bv_month
     */
    public void setbv_month(String value) {
        ensureVariableManager().setVariableValue("bv_month", value);
    }

    /**
     * Returns the variable value for bv_year.
     * @return variable value for bv_year
     */
    public String getbv_year() {
        Calendar c = Calendar.getInstance();
        return c.get(Calendar.YEAR)+"";
    }

    /**
     * Sets <code>value</code> for variable bv_year.
     * @param value value to bind as bv_year
     */
    public void setbv_year(String value) {
        ensureVariableManager().setVariableValue("bv_year", value);
    }

    /**
     * Returns the bind variable value for bv_emp_id.
     * @return bind variable value for bv_emp_id
     */
    public String getbv_emp_id() {
        if (CommonUtil.getSessionValue(Constants.SESSION_USERID) == null) {
            return "0";
        }else{
           return  CommonUtil.getSessionValue(Constants.SESSION_USERID).toString();
        }
       //return "4588";
    }

    /**
     * Sets <code>value</code> for bind variable bv_emp_id.
     * @param value value to bind as bv_emp_id
     */
    public void setbv_emp_id(String value) {
        setNamedWhereClauseParam("bv_emp_id", value);
    }
}
