package hub.nishat.net.model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 27 15:30:16 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_AtdPostingImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public VO_AtdPostingImpl() {
    }


}
