package hub.nishat.net.model.VO;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 30 10:22:33 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_IntercomDirRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PersonIdDepartment {
            public Object get(VO_IntercomDirRowImpl obj) {
                return obj.getPersonIdDepartment();
            }

            public void put(VO_IntercomDirRowImpl obj, Object value) {
                obj.setPersonIdDepartment((String)value);
            }
        }
        ,
        PersonId {
            public Object get(VO_IntercomDirRowImpl obj) {
                return obj.getPersonId();
            }

            public void put(VO_IntercomDirRowImpl obj, Object value) {
                obj.setPersonId((Number)value);
            }
        }
        ,
        Email {
            public Object get(VO_IntercomDirRowImpl obj) {
                return obj.getEmail();
            }

            public void put(VO_IntercomDirRowImpl obj, Object value) {
                obj.setEmail((String)value);
            }
        }
        ,
        Name {
            public Object get(VO_IntercomDirRowImpl obj) {
                return obj.getName();
            }

            public void put(VO_IntercomDirRowImpl obj, Object value) {
                obj.setName((String)value);
            }
        }
        ,
        Intercom {
            public Object get(VO_IntercomDirRowImpl obj) {
                return obj.getIntercom();
            }

            public void put(VO_IntercomDirRowImpl obj, Object value) {
                obj.setIntercom((String)value);
            }
        }
        ,
        Department {
            public Object get(VO_IntercomDirRowImpl obj) {
                return obj.getDepartment();
            }

            public void put(VO_IntercomDirRowImpl obj, Object value) {
                obj.setDepartment((String)value);
            }
        }
        ,
        Designation {
            public Object get(VO_IntercomDirRowImpl obj) {
                return obj.getDesignation();
            }

            public void put(VO_IntercomDirRowImpl obj, Object value) {
                obj.setDesignation((String)value);
            }
        }
        ,
        Category {
            public Object get(VO_IntercomDirRowImpl obj) {
                return obj.getCategory();
            }

            public void put(VO_IntercomDirRowImpl obj, Object value) {
                obj.setCategory((String)value);
            }
        }
        ,
        IsHod {
            public Object get(VO_IntercomDirRowImpl obj) {
                return obj.getIsHod();
            }

            public void put(VO_IntercomDirRowImpl obj, Object value) {
                obj.setIsHod((String)value);
            }
        }
        ,
        IntercomType {
            public Object get(VO_IntercomDirRowImpl obj) {
                return obj.getIntercomType();
            }

            public void put(VO_IntercomDirRowImpl obj, Object value) {
                obj.setIntercomType((String)value);
            }
        }
        ,
        DepartmentLov1 {
            public Object get(VO_IntercomDirRowImpl obj) {
                return obj.getDepartmentLov1();
            }

            public void put(VO_IntercomDirRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EmployeeLov1 {
            public Object get(VO_IntercomDirRowImpl obj) {
                return obj.getEmployeeLov1();
            }

            public void put(VO_IntercomDirRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IntercomTypeLOV1 {
            public Object get(VO_IntercomDirRowImpl obj) {
                return obj.getIntercomTypeLOV1();
            }

            public void put(VO_IntercomDirRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(VO_IntercomDirRowImpl object);

        public abstract void put(VO_IntercomDirRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PERSONIDDEPARTMENT = AttributesEnum.PersonIdDepartment.index();
    public static final int PERSONID = AttributesEnum.PersonId.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int INTERCOM = AttributesEnum.Intercom.index();
    public static final int DEPARTMENT = AttributesEnum.Department.index();
    public static final int DESIGNATION = AttributesEnum.Designation.index();
    public static final int CATEGORY = AttributesEnum.Category.index();
    public static final int ISHOD = AttributesEnum.IsHod.index();
    public static final int INTERCOMTYPE = AttributesEnum.IntercomType.index();
    public static final int DEPARTMENTLOV1 = AttributesEnum.DepartmentLov1.index();
    public static final int EMPLOYEELOV1 = AttributesEnum.EmployeeLov1.index();
    public static final int INTERCOMTYPELOV1 = AttributesEnum.IntercomTypeLOV1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public VO_IntercomDirRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute PersonIdDepartment.
     * @return the PersonIdDepartment
     */
    public String getPersonIdDepartment() {
        return (String) getAttributeInternal(PERSONIDDEPARTMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PersonIdDepartment.
     * @param value value to set the  PersonIdDepartment
     */
    public void setPersonIdDepartment(String value) {
        setAttributeInternal(PERSONIDDEPARTMENT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PersonId.
     * @return the PersonId
     */
    public Number getPersonId() {
        return (Number) getAttributeInternal(PERSONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PersonId.
     * @param value value to set the  PersonId
     */
    public void setPersonId(Number value) {
        setAttributeInternal(PERSONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Email.
     * @return the Email
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Email.
     * @param value value to set the  Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Name.
     * @return the Name
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Name.
     * @param value value to set the  Name
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Intercom.
     * @return the Intercom
     */
    public String getIntercom() {
        return (String) getAttributeInternal(INTERCOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Intercom.
     * @param value value to set the  Intercom
     */
    public void setIntercom(String value) {
        setAttributeInternal(INTERCOM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Department.
     * @return the Department
     */
    public String getDepartment() {
        String department = (String) getAttributeInternal(DEPARTMENT);
        if (department != null) {
            return department;
        }else{
            return "Not in any hierarchy";
        }
       
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Department.
     * @param value value to set the  Department
     */
    public void setDepartment(String value) {
        setAttributeInternal(DEPARTMENT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Designation.
     * @return the Designation
     */
    public String getDesignation() {
        String pos =  (String) getAttributeInternal(DESIGNATION);
        if (pos != null) {
            return pos.replace("0", " ").replace("2", " ").replace("-", " ") ; 
        }else{
            return "Position Not Found!";
        }
        
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Designation.
     * @param value value to set the  Designation
     */
    public void setDesignation(String value) {
        setAttributeInternal(DESIGNATION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Category.
     * @return the Category
     */
    public String getCategory() {
        return (String) getAttributeInternal(CATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Category.
     * @param value value to set the  Category
     */
    public void setCategory(String value) {
        setAttributeInternal(CATEGORY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IsHod.
     * @return the IsHod
     */
    public String getIsHod() {
        return (String) getAttributeInternal(ISHOD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IsHod.
     * @param value value to set the  IsHod
     */
    public void setIsHod(String value) {
        setAttributeInternal(ISHOD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IntercomType.
     * @return the IntercomType
     */
    public String getIntercomType() {
        return (String) getAttributeInternal(INTERCOMTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IntercomType.
     * @param value value to set the  IntercomType
     */
    public void setIntercomType(String value) {
        setAttributeInternal(INTERCOMTYPE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> DepartmentLov1.
     */
    public RowSet getDepartmentLov1() {
        return (RowSet)getAttributeInternal(DEPARTMENTLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> EmployeeLov1.
     */
    public RowSet getEmployeeLov1() {
        return (RowSet)getAttributeInternal(EMPLOYEELOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> IntercomTypeLOV1.
     */
    public RowSet getIntercomTypeLOV1() {
        return (RowSet)getAttributeInternal(INTERCOMTYPELOV1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
