package hub.nishat.net.model.VO;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;

import view.nishat.net.Helper.CommonUtil;
import view.nishat.net.Helper.Constants;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 07 16:54:01 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_MISSING_MINUTESImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    private Number emp_id;
    private String atd_month;
    public VO_MISSING_MINUTESImpl() {
    }


}
