package hub.nishat.net.model.VO.HR;

import java.util.Calendar;

import oracle.jbo.server.ViewObjectImpl;

import view.nishat.net.Helper.CommonUtil;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 08 17:57:08 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_AttendanceHRImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public VO_AttendanceHRImpl() {
    }

    /**
     * Returns the variable value for bv_month.
     * @return variable value for bv_month
     */
    public String getbv_month() {
        //return (String)ensureVariableManager().getVariableValue("bv_month");
        return CommonUtil.getCurrent(CommonUtil.CURR_MONTH_NAME).toString();
    }

    /**
     * Sets <code>value</code> for variable bv_month.
     * @param value value to bind as bv_month
     */
    public void setbv_month(String value) {
        ensureVariableManager().setVariableValue("bv_month", value);
    }

    /**
     * Returns the variable value for bv_year.
     * @return variable value for bv_year
     */
    public String getbv_year() {
        //return (String)ensureVariableManager().getVariableValue("bv_year");
        return String.valueOf(Calendar.getInstance().get(Calendar.YEAR));
    }

    /**
     * Sets <code>value</code> for variable bv_year.
     * @param value value to bind as bv_year
     */
    public void setbv_year(String value) {
        ensureVariableManager().setVariableValue("bv_year", value);
    }
}
