package hub.nishat.net.model.VO.General;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;

import view.nishat.net.Helper.CommonUtil;
import view.nishat.net.Helper.Constants;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 24 16:16:43 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_EmpHierarchySummaryImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public VO_EmpHierarchySummaryImpl() {
    }


}
