package hub.nishat.net.model.VO.CEO.AM;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 30 18:06:41 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CEOAppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CEOAppModuleImpl() {
    }

    /**
     * Container's getter for VO_Org1.
     * @return VO_Org1
     */
    public ViewObjectImpl getVO_Org1() {
        return (ViewObjectImpl)findViewObject("VO_Org1");
    }

    /**
     * Container's getter for VO_Org2.
     * @return VO_Org2
     */
    public ViewObjectImpl getVO_Org2() {
        return (ViewObjectImpl)findViewObject("VO_Org2");
    }

    /**
     * Container's getter for VO_EmpAttendance1.
     * @return VO_EmpAttendance1
     */
    public ViewObjectImpl getVO_EmpAttendance1() {
        return (ViewObjectImpl)findViewObject("VO_EmpAttendance1");
    }

    /**
     * Container's getter for VL_EmpManager1.
     * @return VL_EmpManager1
     */
    public ViewLinkImpl getVL_EmpManager1() {
        return (ViewLinkImpl)findViewLink("VL_EmpManager1");
    }
}
