package hub.nishat.net.model.VO.Supervisor;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 05 15:45:59 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_LeaveRequestsRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Type {
            public Object get(VO_LeaveRequestsRowImpl obj) {
                return obj.getType();
            }

            public void put(VO_LeaveRequestsRowImpl obj, Object value) {
                obj.setType((String)value);
            }
        }
        ,
        FullNameChild {
            public Object get(VO_LeaveRequestsRowImpl obj) {
                return obj.getFullNameChild();
            }

            public void put(VO_LeaveRequestsRowImpl obj, Object value) {
                obj.setFullNameChild((String)value);
            }
        }
        ,
        ParentPersonId {
            public Object get(VO_LeaveRequestsRowImpl obj) {
                return obj.getParentPersonId();
            }

            public void put(VO_LeaveRequestsRowImpl obj, Object value) {
                obj.setParentPersonId((Number)value);
            }
        }
        ,
        EmpCode {
            public Object get(VO_LeaveRequestsRowImpl obj) {
                return obj.getEmpCode();
            }

            public void put(VO_LeaveRequestsRowImpl obj, Object value) {
                obj.setEmpCode((String)value);
            }
        }
        ,
        ApprovalRequired {
            public Object get(VO_LeaveRequestsRowImpl obj) {
                return obj.getApprovalRequired();
            }

            public void put(VO_LeaveRequestsRowImpl obj, Object value) {
                obj.setApprovalRequired((String)value);
            }
        }
        ,
        AprovedFlag {
            public Object get(VO_LeaveRequestsRowImpl obj) {
                return obj.getAprovedFlag();
            }

            public void put(VO_LeaveRequestsRowImpl obj, Object value) {
                obj.setAprovedFlag((String)value);
            }
        }
        ,
        EndDate {
            public Object get(VO_LeaveRequestsRowImpl obj) {
                return obj.getEndDate();
            }

            public void put(VO_LeaveRequestsRowImpl obj, Object value) {
                obj.setEndDate((Date)value);
            }
        }
        ,
        LeaveId {
            public Object get(VO_LeaveRequestsRowImpl obj) {
                return obj.getLeaveId();
            }

            public void put(VO_LeaveRequestsRowImpl obj, Object value) {
                obj.setLeaveId((Number)value);
            }
        }
        ,
        LeaveType {
            public Object get(VO_LeaveRequestsRowImpl obj) {
                return obj.getLeaveType();
            }

            public void put(VO_LeaveRequestsRowImpl obj, Object value) {
                obj.setLeaveType((Number)value);
            }
        }
        ,
        StartDate {
            public Object get(VO_LeaveRequestsRowImpl obj) {
                return obj.getStartDate();
            }

            public void put(VO_LeaveRequestsRowImpl obj, Object value) {
                obj.setStartDate((Date)value);
            }
        }
        ,
        TotalLeaves {
            public Object get(VO_LeaveRequestsRowImpl obj) {
                return obj.getTotalLeaves();
            }

            public void put(VO_LeaveRequestsRowImpl obj, Object value) {
                obj.setTotalLeaves((Number)value);
            }
        }
        ,
        UserId {
            public Object get(VO_LeaveRequestsRowImpl obj) {
                return obj.getUserId();
            }

            public void put(VO_LeaveRequestsRowImpl obj, Object value) {
                obj.setUserId((String)value);
            }
        }
        ,
        Remaining {
            public Object get(VO_LeaveRequestsRowImpl obj) {
                return obj.getRemaining();
            }

            public void put(VO_LeaveRequestsRowImpl obj, Object value) {
                obj.setRemaining((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(VO_LeaveRequestsRowImpl object);

        public abstract void put(VO_LeaveRequestsRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int TYPE = AttributesEnum.Type.index();
    public static final int FULLNAMECHILD = AttributesEnum.FullNameChild.index();
    public static final int PARENTPERSONID = AttributesEnum.ParentPersonId.index();
    public static final int EMPCODE = AttributesEnum.EmpCode.index();
    public static final int APPROVALREQUIRED = AttributesEnum.ApprovalRequired.index();
    public static final int APROVEDFLAG = AttributesEnum.AprovedFlag.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int LEAVEID = AttributesEnum.LeaveId.index();
    public static final int LEAVETYPE = AttributesEnum.LeaveType.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int TOTALLEAVES = AttributesEnum.TotalLeaves.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int REMAINING = AttributesEnum.Remaining.index();

    /**
     * This is the default constructor (do not remove).
     */
    public VO_LeaveRequestsRowImpl() {
    }

    /**
     * Gets EO_LeaveRequests entity object.
     * @return the EO_LeaveRequests
     */
    public EntityImpl getEO_LeaveRequests() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for the calculated attribute Type.
     * @return the Type
     */
    public String getType() {
        return (String) getAttributeInternal(TYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Type.
     * @param value value to set the  Type
     */
    public void setType(String value) {
        setAttributeInternal(TYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FullNameChild.
     * @return the FullNameChild
     */
    public String getFullNameChild() {
        return (String) getAttributeInternal(FULLNAMECHILD);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FullNameChild.
     * @param value value to set the  FullNameChild
     */
    public void setFullNameChild(String value) {
        setAttributeInternal(FULLNAMECHILD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ParentPersonId.
     * @return the ParentPersonId
     */
    public Number getParentPersonId() {
        return (Number) getAttributeInternal(PARENTPERSONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ParentPersonId.
     * @param value value to set the  ParentPersonId
     */
    public void setParentPersonId(Number value) {
        setAttributeInternal(PARENTPERSONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EmpCode.
     * @return the EmpCode
     */
    public String getEmpCode() {
        return (String) getAttributeInternal(EMPCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EmpCode.
     * @param value value to set the  EmpCode
     */
    public void setEmpCode(String value) {
        setAttributeInternal(EMPCODE, value);
    }

    /**
     * Gets the attribute value for APPROVAL_REQUIRED using the alias name ApprovalRequired.
     * @return the APPROVAL_REQUIRED
     */
    public String getApprovalRequired() {
        return (String) getAttributeInternal(APPROVALREQUIRED);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVAL_REQUIRED using the alias name ApprovalRequired.
     * @param value value to set the APPROVAL_REQUIRED
     */
    public void setApprovalRequired(String value) {
        setAttributeInternal(APPROVALREQUIRED, value);
    }

    /**
     * Gets the attribute value for APROVED_FLAG using the alias name AprovedFlag.
     * @return the APROVED_FLAG
     */
    public String getAprovedFlag() {
        return (String) getAttributeInternal(APROVEDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for APROVED_FLAG using the alias name AprovedFlag.
     * @param value value to set the APROVED_FLAG
     */
    public void setAprovedFlag(String value) {
        setAttributeInternal(APROVEDFLAG, value);
    }

    /**
     * Gets the attribute value for END_DATE using the alias name EndDate.
     * @return the END_DATE
     */
    public Date getEndDate() {
        return (Date) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate.
     * @param value value to set the END_DATE
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for LEAVE_ID using the alias name LeaveId.
     * @return the LEAVE_ID
     */
    public Number getLeaveId() {
        return (Number) getAttributeInternal(LEAVEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LEAVE_ID using the alias name LeaveId.
     * @param value value to set the LEAVE_ID
     */
    public void setLeaveId(Number value) {
        setAttributeInternal(LEAVEID, value);
    }

    /**
     * Gets the attribute value for LEAVE_TYPE using the alias name LeaveType.
     * @return the LEAVE_TYPE
     */
    public Number getLeaveType() {
        return (Number) getAttributeInternal(LEAVETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for LEAVE_TYPE using the alias name LeaveType.
     * @param value value to set the LEAVE_TYPE
     */
    public void setLeaveType(Number value) {
        setAttributeInternal(LEAVETYPE, value);
    }

    /**
     * Gets the attribute value for START_DATE using the alias name StartDate.
     * @return the START_DATE
     */
    public Date getStartDate() {
        return (Date) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate.
     * @param value value to set the START_DATE
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for TOTAL_LEAVES using the alias name TotalLeaves.
     * @return the TOTAL_LEAVES
     */
    public Number getTotalLeaves() {
        return (Number) getAttributeInternal(TOTALLEAVES);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_LEAVES using the alias name TotalLeaves.
     * @param value value to set the TOTAL_LEAVES
     */
    public void setTotalLeaves(Number value) {
        setAttributeInternal(TOTALLEAVES, value);
    }

    /**
     * Gets the attribute value for USER_ID using the alias name UserId.
     * @return the USER_ID
     */
    public String getUserId() {
        return (String) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_ID using the alias name UserId.
     * @param value value to set the USER_ID
     */
    public void setUserId(String value) {
        setAttributeInternal(USERID, value);
    }


    /**
     * Gets the attribute value for the calculated attribute Remaining.
     * @return the Remaining
     */
    public Number getRemaining() {
        return (Number) getAttributeInternal(REMAINING);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Remaining.
     * @param value value to set the  Remaining
     */
    public void setRemaining(Number value) {
        setAttributeInternal(REMAINING, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
