package hub.nishat.net.model.VO.Supervisor;

import oracle.jbo.server.ViewObjectImpl;

import view.nishat.net.Helper.CommonUtil;
import view.nishat.net.Helper.Constants;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 10 15:49:35 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VO_SupervisorOrgChartImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public VO_SupervisorOrgChartImpl() {
    }

    /**
     * Returns the variable value for root.
     * @return variable value for root
     */
    public String getroot() {
        String session =  CommonUtil.getSessionValue(Constants.SESSION_USERID).toString();
        System.out.println("supervisor org chart: "+session);
        //return "1138";
        return session;
    }

    /**
     * Sets <code>value</code> for variable root.
     * @param value value to bind as root
     */
    public void setroot(String value) {
        ensureVariableManager().setVariableValue("root", value);
    }
}
